export const categoryType = {
  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",
};

export const productType = {
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_FAILURE: "GET_PRODUCT_FAILURE",

  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",

  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_FAILURE: "GET_PRODUCT_DETAIL_FAILURE",
};

export const authType = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  SIGNOUT_REQUEST: "SIGNOUT_REQUEST",
  SIGNOUT_SUCCESS: "SIGNOUT_SUCCESS",
  SIGNOUT_FAILURE: "SIGNOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const cartType = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILUE: "ADD_TO_CART_FAILURE",

  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_FAILURE: "GET_CART_FAILURE",

  NO_CART: "NO_CART",
};

export const addressType = {
  GET_ADDRESS_REQUEST: "GET_ADDRESS_REQUEST",
  GET_ADDRESS_SUCCESS: "GET_ADDRESS_SUCCESS",
  GET_ADDRESS_FAILURE: "GET_ADDRESS_fAILURE",

  ADD_ADDRESS_REQUEST: "ADD_ADDRESS_REQUEST",
  ADD_ADDRESS_SUCCESS: "ADD_ADDRESS_SUCCESS",
  ADD_ADDRESS_FAILURE: "ADD_ADDRESS_FAILURE",
};

export const orderType = {
  ORDER_REQUST: "ORDER_REQUST",
  ORDER_SUCCESS: "ORDER_SUCCESS",
  ORDER_FAILURE: "ORDER_FAILURE",

  
  GET_ORDER_HISTORY_REQUEST: "GET_ORDER_HISTORY_REQUEST",
  GET_ORDER_HISTORY_SUCCESS: "GET_ORDER_HISTORY_SUCCESS",
  GET_ORDER_HISTORY_FAILURE: "GET_ORDER_HISTORY_FAILURE",
};
